apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: services
build:
  local:
    push: false
  artifacts:
    - image: nejmimouhsine1/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
    - image: nejmimouhsine1/user-service
      context: user-service
      docker:
        dockerfile: Dockerfile
    - image: nejmimouhsine1/listings-service
      context: listings-service
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/frontend-depl.yaml
    - infra/k8s/redis-depl.yaml
    - infra/k8s/user-depl.yaml
    - infra/k8s/user-mongo.yaml
    - infra/k8s/listings-depl.yaml
    - infra/k8s/listings-mongo.yaml
