apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: elevatex.dev
      http:
        paths:
          - pathType: ImplementationSpecific
            path: '/?(.*)'
            backend:
              service:
                name: frontend-srv
                port:
                  number: 3000
          - pathType: ImplementationSpecific
            path: '/api/users/?(.*)'
            backend:
              service:
                name: user-srv
                port:
                  number: 3001
          - pathType: ImplementationSpecific
            path: '/api/listings/?(.*)'
            backend:
              service:
                name: listings-srv
                port:
                  number: 3002
          - pathType: ImplementationSpecific
            path: '/api/reservations/?(.*)'
            backend:
              service:
                name: reservations-srv
                port:
                  number: 3003
