apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - name: reservations
          image: nejmimouhsine1/reservations-service
          env:
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: JWT_ACCESS_SECRET
            - name: MONGO_URI
              value: 'mongodb://reservations-mongo-srv:27017/reservations'
            - name: ALLOWED_ORIGINS
              value: 'https://elevatex.dev'
---
apiVersion: v1
kind: Service
metadata:
  name: reservations-srv
spec:
  selector:
    app: reservations
  ports:
    - name: reservations
      protocol: TCP
      port: 3003
      targetPort: 3003
