apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-mongo-pvc
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mongo-depl
spec:
  selector:
    matchLabels:
      app: user-mongo
  template:
    metadata:
      labels:
        app: user-mongo
    spec:
      containers:
        - name: user-mongo
          image: mongo
          volumeMounts:
            - name: user-mongo-storage
              mountPath: '/data/db'
      volumes:
        - name: user-mongo-storage
          persistentVolumeClaim:
            claimName: user-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-mongo-srv
spec:
  selector:
    app: user-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
